/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zorkButt;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void someRandomTest(){
        // Arrange
        int x = 7;
        int y = 7;
        // Act
        // Assert
        assertEquals(x, 7);
    }
    @Test void thisIsAnEmptyTest(){
        // This is what i want to assert
    }

    @Test void testReverseArray(){
        // Arrange
        // sut === system under test
        Library sut = new Library();
        String[] testStringArray = {"Zork", "Lemi", "Pardus", "Harvey"}; // -> H, P, L, Z
        // Act
        String[] resultArray = sut.reverse(testStringArray);
        // Assert
        assertArrayEquals(resultArray, new String[]{"Harvey", "Pardus", "Lemi", "Zork"});
        assertTrue(resultArray.length == testStringArray.length);
        assertTrue(resultArray[0] == "Harvey");
    }

    @Test void testReverseIntArray(){
        // Arrange
        Library sut = new Library();
        // Act
//        int[] resultARray = sut.reverse();
        // Assert
        // assert that array was reversed
        // check length, chgeck values, check sum of arrays
    }


}
