/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bakery;

import bakery.bakedGoods.BakedGood;
import bakery.bakedGoods.Donut;
import bakery.bakedGoods.Muffin;

import java.math.BigDecimal;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Muffin newMuffin = new Muffin(BigDecimal.valueOf(2.99),"Blueberry", "Medium", true, List.of(new String[]{"Love"}));

        newMuffin.setBaked(false);

        Donut yumYumDonut = new Donut(BigDecimal.valueOf(1.99), "Original", "Medium", "Circle", true, false);

        Bakery ZorksBorks = new Bakery();
        ZorksBorks.bakedGoods.add(newMuffin);

    }
}
