/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package labSolution;

import java.io.IOException;
import java.nio.file.Path;
import java.util.Arrays;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        System.out.println("command line arguments: " + Arrays.toString(args));
        System.out.println(System.getProperty("user.dir")); // shows what your relative directory is.
//        lintFile("gates.js");
    }

    // Need a method to lint Files
    public static void lintFile(String fileToBeRead) throws IOException {
        // Get a Path
        Path fileToBeLinted = Path.of(fileToBeRead);
        int lineNumber = 0;
        String errorMessage = "";
        // Scanner
        try(Scanner fileScanner = new Scanner(fileToBeLinted)){
            // while file hasNextLine
            while(fileScanner.hasNextLine()){
                errorMessage = "";
                // Grab ahold of the currentLine
                String currentLine = fileScanner.nextLine();
                lineNumber++;
                // check for !endsWith(";")
                if(!currentLine.endsWith(";")){
                    // Check for other conditions
                    if(currentLine.isEmpty() || currentLine.endsWith("{") || currentLine.endsWith("}") || currentLine.contains("if") || currentLine.contains("else")){
                    } else {
                    errorMessage += "Line: " + lineNumber + ": Missing semicolon.\n";
                    System.out.println(errorMessage);

                    }
                        // if all false, sout out error message
                }

            }
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }

    }

    /*
        Write a method that reads a JavaScript file with a given Path, and generates an error message whenever it finds a linethat doesn’t end in a semi-colon.

        Read through the file line by line. Create a string that contains a message such as "Line 3: Missing semicolon." if a line is missing a semicolon.

        Don’t show an error if the line is empty.
        Don’t show an error if the line ends with an opening curly brace {
        Don’t show an error if the line ends with an closing curly brace }
        Don’t show an error if the line contains if or else
        Call that method in your main method on the file gates.js, and print out the resulting error message.
    */
}
