/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package zorkButt;

import java.util.ArrayList;

public class Library {

    public boolean someLibraryMethod() {
        return true;
    }

    // What's different between Arrays and ArrayLists
        // ArrayList has methods
        // Array has no methods.
            // has properties -> .length

    // TODO: create the reverseArray method with Java Arrays
    public String[] reverse(String[] arrayToReverse){
        String[] newArray = new String[arrayToReverse.length];
        for (int i = 0; i < arrayToReverse.length ; i++) {
            System.out.println("Yay");
            newArray[(arrayToReverse.length-1) -i] = arrayToReverse[i];
        }
        return newArray;
    }

    // TODO: create reverse method with ArrayLists
    // Polymorphism -> method overloading
    public ArrayList<String> reverse(ArrayList<String> arrayToReverse){
        ArrayList<String> newArray = new ArrayList<>();
        for (int i = arrayToReverse.size(); i >= 0 ; i--) {
            newArray.add(arrayToReverse.get(i));
        }
        return newArray;
    }

    public void reverse(int[] intArray){
        //
    }
}
