/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import com.google.gson.Gson;

import java.util.ArrayList;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Gson gson = new Gson();
        // Reference: https://github.com/google/gson/blob/master/UserGuide.md#TOC-Gson-With-Gradle

        Integer int1 = 1;
        int int2 = 2;
        String jsonReturn = gson.toJson(int1); // --> "1"
        String jsonReturn2 = gson.toJson(int2); // --> "1"
        String[] strArray = {"Blue", "Green", "Purple"};
        String strArrJson = gson.toJson(strArray); // -> ["Blue","Green","Purple"]
        String stringyArray = "[\"Blue\",\"Green\",\"Purple\"]";



        // fromJSON to java --> Need type
        Integer one = gson.fromJson("1", Integer.class);
        Long long1 = gson.fromJson("230", long.class);
        Boolean notTrue = gson.fromJson("false", Boolean.class);
        String[] strArray1 = gson.fromJson("[\"abc\"]", String[].class);
        String[] stringryArrayToJava = gson.fromJson(stringyArray, String[].class);
        for (String color: stringryArrayToJava ){
            System.out.println(color);
        }

        // OBJECTS
        List<String> colors = new ArrayList<>();
        colors.add("Blue");
        colors.add("Pink");
        Unicorn unicorn = new Unicorn(7, 4, true, colors);
        // Unicorn object and turn it into JSON
        String jsonicorn = gson.toJson(unicorn);
        // missing hooves!
        String darkicorn = "{\"hornLength\":20,\"isMajestic\":false,\"colors\":[\"Dark\",\"Black\"]}";
        Unicorn dariconRevived = gson.fromJson(darkicorn, Unicorn.class);


        /*
        {"hornLength":7,"hooves":4,"isMajestic":true,"colors":["Blue","Pink"]}
        {"hornLength":20,"hooves":3,"isMajestic":false,"colors":["Dark","Black"]}

         */

    }
}
