/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ZorksPettingZoo;

import ZorksPettingZoo.animals.Animal;
import ZorksPettingZoo.animals.Goat;
import org.checkerframework.checker.units.qual.A;

public class Library {
    public boolean someLibraryMethod() {
//        Animal newAnimal = new Animal();
        return true;
    }
}
