/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ZorksPettingZoo;

import ZorksPettingZoo.animals.Goat;
import ZorksPettingZoo.animals.Llama;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void llamaNoiseTest(){
        //arrange
        Llama newLlama = new Llama(true, 70, 4, "Kuzco", "white");
        //act
        //assert
        assertSame("clop clop clop", newLlama.move());
    }
}
