/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ZorksPettingZoo;

import ZorksPettingZoo.animals.Animal;
import ZorksPettingZoo.animals.Goat;
import ZorksPettingZoo.animals.Lemur;
import org.checkerframework.checker.units.qual.A;

public class Library {

    public static void main(String[] args){
        Lemur zimbomafoo = new Lemur(true, 8, 2, "zimbomafoo", "grey");
//        zimbomafoo.
    }

    public boolean someLibraryMethod() {
//        Animal newAnimal = new Animal();
        return true;
    }
}
